/-
Copyright (c) 2024 Mike Purvis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import QRTour.QuadraticResidues
import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots

/-!
# Primitive Roots and Subgroup Generators

This module generalizes `QRGenerator` to arbitrary subgroup generators of `(ZMod p)ˣ`.

## Main Definitions

* `QRTour.FullGenerator` - An element g with order p - 1 (a primitive root)
* `QRTour.SubgroupGenerator` - An element g with order d where d | (p - 1)

## Main Results

* `QRTour.full_generator_generates_all` - Powers of a full generator enumerate all units
* `QRTour.full_generator_exists` - Primitive roots exist for any prime
* `QRTour.full_implies_qr_square` - g² is a QR generator when g is a full generator
* `QRTour.qr_generator_is_subgroup_generator` - QR generators are subgroup generators with d = (p-1)/2

## Hierarchy

```
FullGenerator g (order p-1)
       │
       │ g²
       ▼
QRGenerator k (order (p-1)/2)
       │
       ▼
SubgroupGenerator g d (order d | p-1)
```
-/

namespace QRTour

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/-! ### Full Generator (Primitive Root) -/

/-- A full generator (primitive root) is a unit with order p - 1, generating all of (ZMod p)ˣ. -/
structure FullGenerator (g : (ZMod p)ˣ) : Prop where
  /-- The order equals the group size -/
  order_eq : orderOf g = p - 1

/-! ### Subgroup Generator -/

/-- A subgroup generator has order d where d divides p - 1. -/
structure SubgroupGenerator (g : (ZMod p)ˣ) (d : ℕ) : Prop where
  /-- The order equals d -/
  order_eq : orderOf g = d
  /-- d divides p - 1 -/
  divides : d ∣ p - 1

/-! ### Full Generator Properties -/

/-- Powers of a full generator enumerate all units. -/
theorem full_generator_generates_all (hp_ge_2 : 2 ≤ p) (g : (ZMod p)ˣ) (hg : FullGenerator g) :
    ∀ a : (ZMod p)ˣ, ∃ j : ℕ, j < p - 1 ∧ g ^ j = a := by
  intro a
  -- The subgroup generated by g equals the entire group
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units p]
  have hzpowers : Nat.card (Subgroup.zpowers g) = p - 1 := by
    rw [Nat.card_zpowers, hg.order_eq]
  -- Since zpowers g has the same cardinality as the whole group, they're equal
  have hzpowers_eq : Subgroup.zpowers g = ⊤ := by
    apply Subgroup.eq_top_of_card_eq
    rw [hzpowers, hcard]
  -- So a ∈ zpowers g
  have ha_mem : a ∈ Subgroup.zpowers g := by
    rw [hzpowers_eq]
    trivial
  -- Get the integer exponent
  obtain ⟨z, hz⟩ := Subgroup.mem_zpowers_iff.mp ha_mem
  -- Reduce modulo p - 1
  have hp_pos : 0 < p - 1 := by omega
  use (z % ((p : ℤ) - 1)).toNat
  constructor
  · have hmod_nonneg : 0 ≤ z % ((p : ℤ) - 1) := Int.emod_nonneg z (by omega)
    have hmod_lt : z % ((p : ℤ) - 1) < (p : ℤ) - 1 := Int.emod_lt_of_pos z (by omega)
    omega
  · rw [← zpow_natCast, Int.toNat_of_nonneg (Int.emod_nonneg z (by omega))]
    have heq : g ^ (z % ((p : ℤ) - 1)) = g ^ z := by
      rw [zpow_eq_zpow_iff_modEq, hg.order_eq]
      convert Int.mod_modEq z ((p : ℤ) - 1) using 2
      omega
    rw [heq, hz]

/-- Full generators exist for any prime (cyclic group has a generator). -/
theorem full_generator_exists (_hp_ge_2 : 2 ≤ p) : ∃ g : (ZMod p)ˣ, FullGenerator g := by
  -- (ZMod p)ˣ is cyclic, so it has a generator
  have : IsCyclic (ZMod p)ˣ := inferInstance
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := (ZMod p)ˣ)
  use g
  constructor
  -- orderOf g = card of group = p - 1
  have hcard : Fintype.card (ZMod p)ˣ = p - 1 := ZMod.card_units p
  rw [← hcard]
  -- g generates the whole group, so orderOf g = card
  rw [orderOf_eq_card_of_forall_mem_zpowers hg, Nat.card_eq_fintype_card]

/-- The orbit of a full generator has exactly p - 1 elements. -/
theorem full_generator_orbit_card (_hp_ge_2 : 2 ≤ p) (g : (ZMod p)ˣ) (hg : FullGenerator g) :
    Finset.card (Finset.image (fun j => g ^ j) (Finset.range (p - 1))) = p - 1 := by
  have h_injOn : Set.InjOn (fun j => g ^ j) (Finset.range (p - 1)) := by
    intro i hi j hj hij
    rw [Finset.coe_range, Set.mem_Iio] at hi hj
    simp only at hij
    rw [pow_eq_pow_iff_modEq] at hij
    rw [hg.order_eq] at hij
    exact Nat.ModEq.eq_of_lt_of_lt hij hi hj
  rw [Finset.card_image_of_injOn h_injOn, Finset.card_range]

/-! ### Connection to QR Generator -/

/-- g² has order (p-1)/2 when g has order p-1 and p is odd. -/
theorem sq_order_eq_half (hp_odd : p ≠ 2) (g : (ZMod p)ˣ) (hg : FullGenerator g) :
    orderOf (g ^ 2) = half p := by
  -- orderOf (g^2) = orderOf g / gcd(orderOf g, 2)
  rw [orderOf_pow, hg.order_eq]
  -- gcd(p-1, 2) = 2 for odd prime p (since p-1 is even)
  have hp_odd' : Even (p - 1) := hp.out.even_sub_one hp_odd
  have hgcd : Nat.gcd (p - 1) 2 = 2 := by
    obtain ⟨k, hk⟩ := hp_odd'
    rw [hk, ← Nat.two_mul, Nat.gcd_comm]
    -- gcd 2 (2*k) = 2 * gcd 1 k = 2
    calc Nat.gcd 2 (2 * k) = 2 * Nat.gcd 1 k := Nat.gcd_mul_left 2 1 k
      _ = 2 * 1 := by rw [Nat.gcd_one_left]
      _ = 2 := by ring
  rw [hgcd]
  rfl

/-- g² is a quadratic residue (it's a square!). -/
theorem sq_isSquare (g : (ZMod p)ˣ) : IsSquare ((g ^ 2 : (ZMod p)ˣ) : ZMod p) := by
  use g.val
  -- Need: ↑g * ↑g = ↑(g ^ 2)
  rw [sq, Units.val_mul]

/-- The square of a full generator is a QR generator. -/
theorem full_implies_qr_square (hp_odd : p ≠ 2) (g : (ZMod p)ˣ) (hg : FullGenerator g) :
    QRGenerator (g ^ 2) where
  isSquare := sq_isSquare g
  order_eq_half := sq_order_eq_half hp_odd g hg

/-! ### QR Generator as Subgroup Generator -/

/-- A QR generator is a subgroup generator with d = (p-1)/2. -/
theorem qr_generator_is_subgroup_generator (hp_odd : p ≠ 2) (k : (ZMod p)ˣ)
    (hk : QRGenerator k) : SubgroupGenerator k (half p) where
  order_eq := hk.order_eq_half
  divides := by
    use 2
    rw [mul_comm]
    exact half_spec p hp_odd

/-- A full generator is a subgroup generator with d = p - 1. -/
theorem full_generator_is_subgroup_generator (g : (ZMod p)ˣ)
    (hg : FullGenerator g) : SubgroupGenerator g (p - 1) where
  order_eq := hg.order_eq
  divides := dvd_refl _

/-! ### Subgroup Generator Enumeration -/

/-- Powers of a subgroup generator enumerate exactly d distinct elements. -/
theorem subgroup_generator_orbit_card (g : (ZMod p)ˣ) (d : ℕ) (hg : SubgroupGenerator g d)
    (_hd_pos : 0 < d) :
    Finset.card (Finset.image (fun j => g ^ j) (Finset.range d)) = d := by
  have h_injOn : Set.InjOn (fun j => g ^ j) (Finset.range d) := by
    intro i hi j hj hij
    rw [Finset.coe_range, Set.mem_Iio] at hi hj
    simp only at hij
    rw [pow_eq_pow_iff_modEq] at hij
    rw [hg.order_eq] at hij
    exact Nat.ModEq.eq_of_lt_of_lt hij hi hj
  rw [Finset.card_image_of_injOn h_injOn, Finset.card_range]

/-- Powers of a subgroup generator enumerate all elements with that order divisor property. -/
theorem subgroup_generator_generates (g : (ZMod p)ˣ) (d : ℕ) (hg : SubgroupGenerator g d)
    (hd_pos : 0 < d) :
    ∀ a : (ZMod p)ˣ, a ∈ Subgroup.zpowers g → ∃ j : ℕ, j < d ∧ g ^ j = a := by
  intro a ha
  obtain ⟨z, hz⟩ := Subgroup.mem_zpowers_iff.mp ha
  use (z % (d : ℤ)).toNat
  constructor
  · have hmod_nonneg : 0 ≤ z % (d : ℤ) := Int.emod_nonneg z (by omega)
    have hmod_lt : z % (d : ℤ) < d := Int.emod_lt_of_pos z (by omega)
    omega
  · rw [← zpow_natCast, Int.toNat_of_nonneg (Int.emod_nonneg z (by omega))]
    have heq : g ^ (z % (d : ℤ)) = g ^ z := by
      rw [zpow_eq_zpow_iff_modEq, hg.order_eq]
      exact Int.mod_modEq z d
    rw [heq, hz]

/-! ### Connection to Mathlib's IsPrimitiveRoot -/

/-- A full generator is equivalent to Mathlib's IsPrimitiveRoot. -/
theorem fullGenerator_iff_isPrimitiveRoot (g : (ZMod p)ˣ) :
    FullGenerator g ↔ IsPrimitiveRoot g (p - 1) := by
  constructor
  · intro hg
    rw [IsPrimitiveRoot.iff_orderOf]
    exact hg.order_eq
  · intro hg
    constructor
    rw [← IsPrimitiveRoot.iff_orderOf]
    exact hg

end QRTour
